### ISSUE TITLE
Specifying additional build dependencies

### ISSUE THREAD

**Issue by Panaetius** [bneijt/poetry-lock-package#24]
Our package uses the (inofficial) `build.py` support of poetry to execute additional build actions.

When running `poetry-lock-package` this file isn't copied to the `project-lock` directory.

I can easily do `mkdir project-lock && cp build.py project-lock/` to fix this. 

But I wanted to ask if there is an option to specify files that need to be copied over?

Thanks!

**Comment by bneijt** [comment]
The lock package depends on the original package, so if there are steps during install that need to happen it would be picked up by the original package. If the build.py does extra steps to create extra information inside the lock package, then that would also not really be required as the lock package is just an empty package that strongly depends on all the locked versions from your `poetry.lock` file.

Could you give an example of what the `build.py` file does and why that is also something you would like the lock package?

**Comment by Panaetius** [comment]
You're right, we don't need the build script in the lock package, my bad.

But in that case, the problem is that the build script entry in the root `pyproject.toml` gets copied to the `pyproject.toml` of the lock package (which in turn causes it to fail to build).

**Comment by bneijt** [comment]
Please try 0.4.5 for a fix. Thank you for submitting this issue!
