### ISSUE TITLE
Poetry 1.3.1 has lock file change that breaks --build

### ISSUE THREAD

**Issue by bneijt** [bneijt/poetry-lock-package#31]
New lock package format has a `files` attributes, which will get copied to the lock `pyproject.toml` and fail to build.

We should filter out the package metadata from the lock file to keep this from happening.

**Comment by bschollnick** [comment]
Is this still an issue?  It's been merged and #32 appears to be closed.  But this original, merged ticket is still open?  Should this be closed, since it's been resolved (??) with #32 ?

**Comment by bneijt** [comment]
No, good point, should not be an issue.
